INSERT INTO pi_campaign (id, deleted, appealBegin, appealEnabled, appealEnd, classificationBanner, classificationBtnText, closed, deactivationAlertEnabled, description, dummyInstitution, institutionGroupRanked, institutionRanked, labelDeactivationInstitutionText, labelDeactivationInstitutionTooltip, labelDeactivationUserText, labelDeactivationUserTooltip, labelDummyInstitution, labelInstitutionGroup, labelInstitutionSelection, labelMyInstitution, labelRules, participativeEvaluated, title, userRanked, company_id, rules_id) VALUES
(3, b'0', NULL, b'0', NULL, NULL, 'Classificação', b'0', b'0', '<ol><li><span style="font-family: arial; font-size: medium;"><span style="color: rgb(0, 0, 0); background-color: rgb(253, 244, 244);">Prêmio para pró-reitoria, departamento ou setor:</span><span style="color: rgb(255, 255, 255); background-color: rgb(253, 244, 244);">&nbsp;R$100.000,00 (1º colocado)</span></span><br></li></ol>', b'1', b'0', b'0', '<p>A pontuação de sua instituição pode ter sido reduzida devido à desativação da conta de {0} usuários que realizaram ações que geraram pontos à ela.</p><p>Lavras, {1}.</p>', 'A pontuação de sua instituição pode ter sido reduzida devido à desativação da conta de {0} usuários que realizaram ações que geraram pontos à ela.', '<p>A sua pontuação pode ter sido reduzida devido à desativação da conta de {0} usuários que interagiram com suas ideias.</p><p>Lavras, {1}.</p>', 'A sua pontuação pode ter sido reduzida devido à desativação da conta de {0} usuários que interagiram com suas ideias.', 'Sem instituição', 'Grupo Institucional', 'Selecione sua instituição', 'Minha instituição', 'Edital', b'0', 'Rodada de desafios #1', b'0', 1, NULL);
INSERT INTO pi_company (id, deleted, accessToken, category, community, createdAt, description, facebookId, fanPage, link, name, photoLink, defaultLocale, headerImage, loadingImage, mobileWelcomeImage, theme, shortName) VALUES
(3, b'0', '', 'ensino', b'0', '2015-12-14 15:37:35', NULL, NULL, b'0', 'http://www.progolden.com.br/', 'progolden', 'https://pbs.twimg.com/profile_images/3662114136/5cb4a053c98007e3be3e2cabbe4328e3_400x400.jpeg', 'pt_BR', '', '', '', 4, 'pg');
INSERT INTO pi_company_domain (host, appleStoreUrl, baseUrl, playStoreUrl, portalEnabled, company_id) VALUES
('localhost:8080', NULL, 'http://localhost:8080/ProIdea/', NULL, b'0', 1);
INSERT INTO pi_game (id, deleted, begin, blockSimpleComment, commentPreviousModeration, dailyIdeasLimit, description, descriptionLabel, end, ideaBox, ideaBoxClosed, ideaPreviousModeration, fiveStarDescription, fourStarDescription, oneStarDescription, theme, threeStarDescription, twoStarDescription, numberOfComments, numberOfIdeas, numberOfLikes, numberOfPermitedWordsInComment, password, photoLink, privateParticipation, reward, rewardDescription, postComment, postDislike, postIdea, postLike, receiveComment, receiveDislike, receiveLike, receiveUserLike, sponsorPhotoLink, title, titleLabel, validUserRequired, weekIdeasLimit, campaign_id, company_id) VALUES
(3, b'0', '2015-12-16 10:17:00', b'0', b'0', 0, 'acabe com o mosquito', 'Explique e justifique a importância de sua ideia', '2016-12-16 10:00:00', b'0', b'0', b'0', 'Contribuição de impacto alto com alta contribuição financeira (direta ou indiretamente): 25 pontos.', 'Contribuição de impacto alto (contribuição para toda organização, com alta repercussão): 16 pontos.', 'Não implementável ou custo/beneficio desfavorável: 1 ponto.', '', 'Contribuição de impacto médio (contribuição para todo setor ou produto): 9 pontos.', 'Contribuição de impacto baixo (limitado a uma função ou serviço): 4 pontos.', 0, 0, 0, 0, NULL, 'http://promanager.progolden.com.br/prostorager/file/2373', b'0', '1000', 'para o &nbsp;primeiro', 1, 0, 5, 1, 1, 0, 1, 15, NULL, 'Como acabar com o mosquito', 'Ideia', b'1', 0, 1, 1);
INSERT INTO pi_portal (about, bannerBtnText, bannerTitle, callFile, callText, captchaSecretkey, captchaSitekey, copyright, description, fbName, fbPage, homeBanner, howWorks, importance, keywords, logo, name, privacy, sponsors, steps, supporters, terms, whenn, domain_host) VALUES
('UFLA+ Soluções Inovadoras é uma consulta pública promovida pela Universidade Federal de Lavras para prospectar inovações na instituição por meio da participação social.', 'Comece Agora', 'Participe do PrêmioIdeia', '<a href = ''http://www.ufla.br/''>Descricao</a>', 'Chamada Publica', '6LdkkAwTAAAAAI2NwdrFME1L1Io-hktK7fbf45Cs', '6LdkkAwTAAAAAGqudt7BKGUSROGwG9WhTHnEjfGR', 'ufla', 'Descrição', NULL, NULL, 'http://promanager.progolden.com.br/prostorager/file/2362', 'Você pode enviar ideias, curtir, comentar e compartilhar outras ideias. A cada interação, você acumula pontos para disputar ótimos prêmios. Clique aqui e veja como participar.', 'Participando dos desafios de ideias desta consulta, você irá contribuir com a identificação e avaliação de soluções inovadoras para impulsionar o desenvolvimento institucional da UFLA.', 'Palavras-chave', 'http://promanager.progolden.com.br/prostorager/file/2354', 'progolden', 'http://www.ufla.br/', '<a href="http://www.ufla.br/" target="_blank" title="Ir para o site"><img src="http://www.eventos.ufla.br/iiiselem/images/ufla.png" alt="UFLA"></a>', 'http://promanager.progolden.com.br/prostorager/file/2363', '<a href="http://www.ufla.br/" target="_blank" title="Ir para o site"><img src="http://www.eventos.ufla.br/iiiselem/images/ufla.png" alt="UFLA"></a>', 'http://www.ufla.br/', 'A consulta iniciará às 16:00 (horário de Brasília) de 27 de maio de 2015. Clique aqui para consultar a Chamada Pública. Todos os cidadãos são convidados a participar desse grande desafio de ideias.', 'localhost:8080');
INSERT INTO pi_user (id, deleted, accessLevel, accessToken, activationCode, cellPhoneNumber, createdAt, creationIpAddress, dateOfBirth, email, emailValidated, emailValidationIpAddress, facebookId, genre, link, linkedinId, locale, location, name, password, phoneValidated, phoneValidationIpAddress, photoLink, pretendedCellPhone, smsCode, smsCodesRequired, smsLastRequire, smsValidationsTried, suspect, username, verified, zipCode) VALUES
(3, b'0', 10, '', NULL, '(35) 9911-91991', '2015-12-14 15:33:57', '127.0.0.1', '1990-01-01', 'teste@gmail.com', b'0', NULL, NULL, NULL, '', NULL, 'pt_BR', 'Lavras - MG', 'Teste Progolden', 'Bcu-d0aCUgs', b'0', NULL, '/ProIdea/public/default/img/icon_user.png', '', NULL, 0, NULL, 0, b'0', '273.124.144-60', b'0', '37200-000');
INSERT INTO pi_user_browser (id, cookieId, createdAt, userAgent) VALUES
(3, '0', '2015-12-14 15:25:37', 'Not available'),
INSERT INTO pi_user_login_log (id, browserCookieId, browserId, ipAddress, loggedAt, userCellPhone, userEmail, userFacebookId, userId, userName, userZipCode) VALUES
(3, 'HUowjqGL4RGaBXLJl9omLA', 2, '127.0.0.1', '2015-12-14 15:36:37', '(35) 9911-91991', 'teste@gmail.com', NULL, 1, 'Teste Progolden', '37200-000'),
